---
- hosts: all
  become: yes
  tasks:
    #- name: ensure basic packages
    #  pkgng: name=git,vim-console,zsh,bash,screen,wrk,gdb state=present
    - name: disable noisy banner which kills fabric
      lineinfile: >-
        dest='{{home}}/.profile'
        regexp='.*freebsd\-tips.*'
        state=absent
    - name: link /bin/bash
      shell: "! [ -f /bin/bash ] && ln -s /usr/local/bin/bash /bin/bash || true"
    - name: /bin/bash in /etc/shells
      lineinfile: >-
        dest=/etc/shells
        create=no
        state=present
        line='/bin/bash'
    - name: kernel dump
      lineinfile: >-
        dest=/etc/rc.conf
        create=no
        state=present
        line='dumpdev="AUTO"'
    - name: kernel dump
      lineinfile: >-
        dest=/etc/rc.conf
        create=no
        state=present
        line='dumpdir="/var/crash"'
    - name: make /var/crash
      file: path=/var/crash owner=root mode=0700 state=directory
    - name: make /usr/src
      file: path=/usr/src owner={{user}} mode=0777 state=directory
    - name: make /usr/obj
      file: path=/usr/obj owner={{user}} mode=0777 state=directory
