---
- name: ensure basic packages
  become: yes
  apt: name={{ item }} state=present update_cache=yes
  with_items:
  - git
  - vim-nox
  - zsh
  - screen
  - python3-pip
- name: set PATH for bash
  lineinfile: >-
    dest={{home}}/.bash_profile
    create=yes
    state=present
    line='export PATH=$PATH:/sbin:/usr/sbin:/usr/local/sbin'
- name: make ~/deployed
  file: path={{home}}/deployed state=directory

- name: create /etc/init/ttyS0.conf
  become: yes
  blockinfile:
    dest: /etc/init/ttyS0.conf
    create: yes
    state: present
    block: |
      start on stopped rc RUNLEVEL=[2345]
      stop on runlevel [!2345]
      respawn
      exec /sbin/getty -8 115200 ttyS0

- name: grub cmd line for subsequent kernel install
  become: yes
  lineinfile:
    dest: /etc/default/grub
    create: no
    state: present
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash console=tty0 console=ttyS0,115200"'

- name: Apply grub configuration
  become: yes
  shell: update-grub
