---
- name: Install dependencies of PyTorch Geometoric in virtualenv
  pip:
    name: "{{ item }}"
    virtualenv: "{{ venv_root }}/pytorch_env"
    virtualenv_python: python3.7
  loop:
    - scikit-learn
    - scipy
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - torch-spline-conv
    - networkx
    - plyfile
    - pandas
    - rdflib
    - h5py
    - decorator
    - python-dateutil
    - pytz
    - pyparsing
    - isodate
    #    - torch-geometric
