- name: install common Debian packages
  become: yes
  apt:
    pkg: ['vim-nox', 'build-essential', 'zlib1g-dev', 'autoconf',
          'automake', 'pkg-config', 'git', 'libncurses5-dev',
          'ethtool', 'xserver-xorg', 'libdb-dev',
          'libelf-dev', 'libssl-dev', 'bzr', 'tcpdump',
          'screen', 'zsh', 'rsync', 'xfsprogs', 'hfsprogs', 'curl',
          'libnuma-dev', 'libbsd-dev']
    update_cache: yes
    state: latest

#- name: set PATH for bash
#  become: yes
#  lineinfile: >-
#    dest={{home}}/.bash_profile
#    create=yes
#    state=present
#    line='export PATH=$PATH:/sbin:/usr/sbin:/usr/local/sbin'
