---
#- file: path={{ ansible_env.HOME }}/deployed state=directory follow=yes
  #- include: main-debian.yml
  #when: ansible_os_family == 'Debian'
  #
- name: create /etc/init/ttyS0.conf
  become: yes
  blockinfile:
    dest: /etc/init/ttyS0.conf
    create: yes
    state: present
    block: |
      start on stopped rc RUNLEVEL=[2345]
      stop on runlevel [!2345]
      respawn
      exec /sbin/getty -8 115200 ttyS0

- name: grub cmd line for subsequent kernel install
  become: yes
  lineinfile:
    dest: /etc/default/grub
    create: no
    state: present
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash console=tty0 console=ttyS0,115200"'

- name: Apply grub configuration
  become: yes
  shell: update-grub
