- name: copy X1C.map
  become: yes
  ignore_errors: true
  copy: # XXX we just need X1C.map
    src: /usr/share/keymaps
    dest: /usr/share

- name: copy systemd service file
  become: yes
  copy:
    src: /etc/systemd/system/loadkeys.service
    dest: /etc/systemd/system/loadkeys.service
    mode: '0644'

- name: reload systemd 
  become: yes
  systemd:
    name: loadkeys.service
    state: started
    enabled: yes

