- name: install common Debian packages
  become: yes
  apt:
    pkg: ['build-essential', 'zlib1g-dev', 'autoconf',
          'automake', 'pkg-config', 'git', 'mercurial', 'libncurses5-dev',
          'ethtool', 'xserver-xorg', 'libdb-dev', 'bison', 'flex',
          'libelf-dev', 'libssl-dev', 'python-bzrlib', 'bzr', 'tcpdump',
          'screen', 'zsh', 'python3-pip', 'rsync', 'xfsprogs', 'dtach', 'curl',
          'bc', 'libnuma-dev']
    update_cache: yes
    state: latest
